export type RecipeGroup =
  | 'basics'        // beginner building blocks. the smallest pieces explained
  | 'starters'
  | 'pyramid'       // static per-reel shape
  | 'multiways'     // per-spin row variation
  | 'big-symbols'   // N×M block symbols
  | 'wilds'         // sticky/expanding/walking/multiplier wilds
  | 'features'      // bonus reveals, multipliers, coins, transforms
  | 'cascade'       // cascade physics + tumbling
  | 'wins'          // payline & cell-highlight presentation
  | 'tension'       // anticipation, near-miss, skip, respin
  | 'cell-coords'   // cell bounds, hit areas, overlays
  | 'symbol-formats' // texture atlas, animated, AI-generated
  | 'runtime';      // mode swaps, feature middleware

export interface RecipeMeta {
  slug: string;
  group: RecipeGroup;
  title: string;
  oneLiner: string;
  steps: string[];
  apis: string[];
  tags: string[];
  /**
   * Card preview, OPTIONAL. By convention you don't set this: drop a file at
   * `public/recipes/<slug>/card.<ext>` (gif / webp / png / mp4 ...) and it is
   * picked up automatically. With no file the card renders a generated
   * placeholder from the title. Set this only to point at a non-conventional
   * path. See the "Recipe previews" guide and `lib/recipeMedia.ts`.
   */
  image?: string;
}

/** Display order + label for each group on the /recipes/ index page. */
export const RECIPE_GROUPS: Array<{ id: RecipeGroup; label: string; description: string }> = [
  {
    id: 'basics',
    label: 'Building blocks (start here)',
    description: 'The smallest pieces, explained step by step. how a symbol class works, how a coin carries a value.',
  },
  {
    id: 'starters',
    label: 'Starter templates',
    description: 'Copy-paste foundations to clone for a new slot.',
  },
  {
    id: 'pyramid',
    label: 'Per-reel geometry (pyramid layouts)',
    description: 'Static jagged shapes. non-uniform row counts fixed at build time.',
  },
  {
    id: 'multiways',
    label: 'MultiWays',
    description: 'Per-spin row variation. each reel can land on a different row count between minRows and maxRows.',
  },
  {
    id: 'big-symbols',
    label: 'Big symbols (N×M blocks)',
    description: 'Single symbol that occupies an N×M block of cells. 2×2 bonuses, 3×3 giants, 1×3 bars.',
  },
  {
    id: 'wilds',
    label: 'Wilds & sticky cells',
    description: 'Sticky, expanding, walking, multiplier wilds. all powered by the pin primitive.',
  },
  {
    id: 'features',
    label: 'Features, bonuses & transforms',
    description: 'Mystery reveals, value coins, collectors, symbol upgrades.',
  },
  {
    id: 'cascade',
    label: 'Cascade & tumbling',
    description: 'Drop physics, anticipation drops, removing winners.',
  },
  {
    id: 'wins',
    label: 'Wins & paylines',
    description: 'Highlight winning cells; draw your own paylines from events.',
  },
  {
    id: 'tension',
    label: 'Anticipation, skip & respin',
    description: 'Slow a reel, slam-stop, near-miss, single-reel respin.',
  },
  {
    id: 'cell-coords',
    label: 'Cell coordinates & hit areas',
    description: 'Pixel rects per cell; pointer-aligned overlays.',
  },
  {
    id: 'symbol-formats',
    label: 'Symbol authoring',
    description: 'Texture atlases, animated sprite sequences, AI-generated art.',
  },
  {
    id: 'runtime',
    label: 'Runtime & feature modes',
    description: 'Mid-spin mode swaps, frame middleware.',
  },
];

/**
 * Every recipe card on /recipes/ comes from this list. The `group` field
 * controls which section the card renders under on the index page.
 */
export const RECIPES: RecipeMeta[] = [
  // ── Building blocks (beginners start here) ─────────────────────────
  {
    slug: 'coin-value-symbol',
    group: 'basics',
    title: 'Beginner: carry a value on a coin',
    oneLiner: 'Build your own symbol class from scratch that draws a coin with a number on it. Learn what a ReelSymbol is, the few methods the engine calls, and how to read the value back.',
    steps: [
      'A symbol is any subclass of ReelSymbol; the engine makes one per cell',
      'Take the value in the constructor and store it',
      'Draw the coin + number in resize() (runs on every swap with the cell size)',
      'Read the value back off the landed symbol instance any time',
    ],
    apis: ['ReelSymbol', 'ReelSetBuilder.symbols', 'Reel.getSymbolAt'],
    tags: ['beginner', 'basics', 'symbol', 'coin', 'value', 'custom-symbol', 'recent'],
  },
  {
    slug: 'coin-value-data',
    group: 'basics',
    title: 'Beginner: carry the value as data',
    oneLiner: 'The same coin, but the number lives in data instead of the class. One generic coin carries any value the server sends, painted from coin:locked. The Hold & Win way.',
    steps: [
      'Keep ONE generic coin symbol with no number baked in',
      "Send the amount in the hit's data: { cell, id: 'coin', data: { value: 25 } }",
      'The board stores data and never reads it',
      'Paint the number yourself from coin:locked, positioned with cellCenter()',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.events', 'HoldAndWinBoard.cellCenter'],
    tags: ['beginner', 'basics', 'coin', 'value', 'data', 'hold-and-win', 'recent'],
  },
  {
    slug: 'coin-value-overlay',
    group: 'basics',
    title: 'Beginner: number on a ready-made coin',
    oneLiner: "Don't draw the coin — use art you already have (a sprite) and add the number on top. Your symbol's view holds two children: the art and a text label.",
    steps: [
      "Put the ready-made coin art (a Sprite) in your symbol's view",
      'Add a PIXI.BitmapText label as a second child, on top',
      'Position and scale both in resize()',
      'The label shows the value; the art does the rest',
    ],
    apis: ['ReelSymbol', 'loadHoldAndWinSprites', 'PIXI.Sprite'],
    tags: ['beginner', 'basics', 'coin', 'value', 'composition', 'sprite', 'recent'],
  },

  // ── Per-reel geometry / MultiWays / Big symbols ───────────────────
  {
    slug: 'pyramid-shape',
    group: 'pyramid',
    title: 'Per-reel shape (pyramid)',
    oneLiner: 'Non-uniform reel set. 3-5-5-5-3 pyramid, diamond, half-pyramid. Static shape set at build time.',
    steps: [
      'Pass an array to .visibleRowsPerReel([3, 5, 5, 5, 3]) instead of .visibleRows(n)',
      'Optionally set .reelAnchor("center" | "top" | "bottom") to control vertical alignment',
      'getCellBounds(col, row) reflects per-reel offsetY automatically',
    ],
    apis: ['ReelSetBuilder.visibleRowsPerReel', 'ReelSetBuilder.reelAnchor', 'Reel.offsetY'],
    tags: ['shape', 'pyramid', 'geometry', 'layout'],
  },
  {
    slug: 'spine-pyramid-shape',
    group: 'pyramid',
    title: 'Pyramid shape with Spine',
    oneLiner: 'Same 3-5-5-5-3 pyramid, every cell a Spine 2D skeleton. Crisp at every per-reel cell size, with idle/landing/win/destroy animations baked in.',
    steps: [
      '`await loadGeneratedSpines()` once before building',
      'Map symbol ids to skeleton names with `buildSpineMap({ id: "low_a", ... })`',
      'Register every id with `SpineReelSymbol`. same registration as a uniform layout',
    ],
    apis: ['SpineReelSymbol', 'loadGeneratedSpines', 'buildSpineMap', 'ReelSetBuilder.visibleRowsPerReel'],
    tags: ['shape', 'pyramid', 'spine', 'custom-symbol', 'animation'],
  },
  {
    slug: 'multiways',
    group: 'multiways',
    title: 'MultiWays',
    oneLiner: 'Per-spin row variation. each reel can land on a different row count between minRows and maxRows.',
    steps: [
      'Build with .multiways({ minRows, maxRows, reelPixelHeight })',
      'Each spin, call reelSet.setShape(rowsPerReel) BEFORE setResult()',
      'AdjustPhase reshapes reels (resize symbols + reshape motion) before STOP',
    ],
    apis: ['ReelSetBuilder.multiways', 'ReelSet.setShape', 'AdjustPhase'],
    tags: ['multiways', 'shape', 'reshape', 'geometry'],
  },
  {
    slug: 'spine-big-symbols',
    group: 'big-symbols',
    title: 'Big symbols with Spine',
    oneLiner: 'Same 2×2 anchor mechanic, every cell a Spine skeleton. The bigWild reuses the regular wild rig. Spine scales it to the larger block without losing crispness.',
    steps: [
      '`await loadGeneratedSpines()` once before building. boots the atlas + 10 skeleton JSONs',
      'Register every id with `SpineReelSymbol` and pass the same map to each registration',
      'Mark the big symbol with `size: { w: 2, h: 2 }` and `weight: 0`. anchor-only, never from random fill',
    ],
    apis: ['SpineReelSymbol', 'loadGeneratedSpines', 'buildSpineMap', 'ReelSetBuilder.symbolData'],
    tags: ['big-symbols', 'spine', 'custom-symbol', 'animation'],
  },
  {
    slug: 'big-symbols-mxn',
    group: 'big-symbols',
    title: 'MxN big symbols. every shape',
    oneLiner: 'Square 2×2, tall 1×3, giant 3×3, wide 2×4. one focused interactive demo per shape, with the placement logic spelled out.',
    steps: [
      'Same registration API for every shape: { weight: 0, size: { w, h } }',
      'Anchor formula: col in [0, REELS - w], row in [0, ROWS - h]',
      'getSymbolFootprint + getBlockBounds resolve any cell to its anchor + pixel rect',
    ],
    apis: ['SymbolData.size', 'ReelSet.getSymbolFootprint', 'ReelSet.getBlockBounds'],
    tags: ['big-symbols', 'layout', 'sizing'],
  },
  {
    slug: 'big-symbol-partial-land',
    group: 'big-symbols',
    title: 'Land a big symbol partially in buffer',
    oneLiner: 'A tall 1xH block lands with its anchor in bufferAbove. Only the bottom cell shows at row 0. Nudge to drag the rest into view. Works end-to-end through setResult, refill, nudge, and the cross-reel resolver.',
    steps: [
      'Pass an anchor at `bufferAbove[i]` via the explicit `ColumnTarget` form (or row -i-1 via legacy negative-index)',
      "Coordinator paints OCCUPIED at the rest of the block's cells (negative rows, visible rows, or bufferBelow as needed)",
      '`_finalizeFrame` sizes the anchor sprite to span the whole block; the mask clips the off-screen portion',
      '`getVisibleSymbols` resolves visible cells to the anchor id via a NEGATIVE `anchorRow` in `_occupancy`',
    ],
    apis: ['ReelSet.setResult', 'ColumnTarget.bufferAbove', 'ColumnTarget.bufferBelow', 'ReelSet.getSymbolFootprint'],
    tags: ['big-symbols', 'buffer', 'nudge', 'recent'],
  },
  {
    slug: 'big-symbol-held-respin',
    group: 'big-symbols',
    title: 'Nudge a big symbol in, then hold it across a respin',
    oneLiner: 'A tall wild lands with its anchor in bufferAbove (tail-visible at row 0). Nudge the trigger reel to drag the full block into view, then call `spin({ holdReels: [...] })` so the revealed wild survives a respin of the other reels. The held strip is never touched.',
    steps: [
      'Land a 1xH wild with its anchor in `bufferAbove` on the trigger reel (only the bottom cell shows at row 0)',
      'Nudge the trigger reel down to drag the full block into visibility',
      'Call `reelSet.spin({ holdReels: [triggerReel] })` to skip START/SPIN/STOP on that column',
      'Pass a full-width grid to `setResult`. The held column entry is ignored; the revealed block stays put',
    ],
    apis: ['ReelSet.spin', 'SpinOptions.holdReels', 'ReelSet.setResult', 'ColumnTarget.bufferAbove', 'ReelSet.nudge'],
    tags: ['big-symbols', 'buffer', 'hold-reels', 'respin', 'nudge', 'recent'],
  },
  {
    slug: 'big-symbol-cascade-fall',
    group: 'big-symbols',
    title: 'Big symbol falls into view through a cascade',
    oneLiner: "A tall wild lands with its tail peeking in from bufferAbove. The cells below the tail form a winning cluster, clear in the cascade, and the wild's anchor falls down through the strip into full visibility.",
    steps: [
      'Land a 1xH wild with its anchor in `bufferAbove`; tail visible at row 0',
      'Plant a winning cluster on a row below the tail so `detectWinners` returns those cells',
      "In `nextGrid`, return a refill grid that places the wild's anchor at a more visible row",
      'The cascade refill animates each strip cell, including the moved anchor sprite, into its new position',
    ],
    apis: ['ReelSet.runCascade', 'ReelSet.setResult', 'ColumnTarget.bufferAbove', 'SymbolData.size', 'ReelSetBuilder.tumble'],
    tags: ['big-symbols', 'buffer', 'cascade', 'tumble', 'recent'],
  },
  {
    slug: 'get-block-bounds',
    group: 'big-symbols',
    title: 'getBlockBounds. outline a big symbol',
    oneLiner: 'Draw a single rectangle that hugs an entire N×M block, regardless of which cell you pass. Works for 1×1 (equivalent to getCellBounds) and 1×N expanding wilds.',
    steps: [
      'getBlockBounds(col, row) returns { x, y, width, height } in ReelSet-local pixels',
      "Pass any cell of a block. anchor or non-anchor. both return the same rect",
      'Use for win frames, cluster outlines, hit-area overlays',
    ],
    apis: ['ReelSet.getBlockBounds', 'ReelSet.getSymbolFootprint'],
    tags: ['big-symbols', 'overlay', 'cell-bounds'],
  },
  {
    slug: 'card-symbol-debug',
    group: 'starters',
    title: 'CardSymbol. debug / prototyping helper',
    oneLiner: 'No-asset PIXI.Graphics symbol class for recipes, mechanic tests, and prototypes. NOT for production. ship Sprite/Animated/Spine instead.',
    steps: [
      "Import CardSymbol, CARD_DECK from `examples/shared/CardSymbol.ts`",
      'Register one symbol id per card with its own color',
      'No textures, no atlases. geometry redrawn at every resize',
    ],
    apis: ['CardSymbol', 'CARD_DECK', 'WILD_CARD', 'PIXI.Graphics'],
    tags: ['debug', 'prototyping', 'custom-symbol', 'graphics'],
  },
  {
    slug: 'empty-symbol',
    group: 'starters',
    title: 'EmptySymbol: render nothing for a registered id',
    oneLiner: 'Register an EmptySymbol against an id like `empty` to reserve a grid slot that produces no visual output. The canonical background for hold-and-win bonus boards, miss cells, and any pattern where "blank" is the intended visual.',
    steps: [
      "Import EmptySymbol from `pixi-reels`",
      "Register the empty id via `r.register('empty', EmptySymbol, {})`",
      'Weight empty heavily so most cells land blank; weight real symbols lightly so they pop',
      'The cell still occupies a strip slot, but renders zero pixels',
    ],
    apis: ['ReelSymbol', 'SymbolRegistry.register', 'ReelSetBuilder.symbols', 'ReelSetBuilder.weights'],
    tags: ['symbols', 'empty', 'hold-and-win', 'recent'],
  },
  {
    slug: 'multiways-cascade',
    group: 'multiways',
    title: 'MultiWays cascade',
    oneLiner: 'Per-spin row variation on a strip-spin landing; cascade tumble pops winners and drops new symbols in from above. Shape-aware on every reel.',
    steps: [
      'Build with .multiways({minRows, maxRows, reelPixelHeight}) + .tumble({...}) for the refill phases',
      'Each round, call setShape(rowsPerReel) BEFORE setResult()',
      'reelSet.spin({ mode: \'standard\' }). strip-spin lands the multiways grid (AdjustPhase reshapes during SPIN→STOP)',
      'reelSet.runCascade({ detectWinners, nextGrid }) tumbles winners and drops new symbols in from above',
    ],
    apis: ['ReelSetBuilder.multiways', 'ReelSetBuilder.tumble', 'ReelSet.setShape', 'ReelSet.runCascade'],
    tags: ['multiways', 'cascade', 'hybrid', 'recent'],
  },
  {
    slug: 'sticky-wild-multiways',
    group: 'multiways',
    title: 'Sticky wild on MultiWays',
    oneLiner: 'Pin survives every MultiWays reshape. clamps when shape shrinks, restores to originRow when it grows back.',
    steps: [
      'Pin wilds on spin:allLanded. originRow is frozen at placement',
      'Each spin, setShape(rowsPerReel). AdjustPhase migrates pins via min(originRow, newRows-1)',
      'pin:migrated fires per affected pin with { fromRow, toRow, clamped, reelIndex }',
    ],
    apis: ['ReelSet.pin', 'CellPin.originRow', 'AdjustPhase', 'pin:migrated event'],
    tags: ['multiways', 'sticky', 'wild', 'cell-pin', 'pin-migration'],
  },

  // ── Starter templates (merged in from /templates/) ─────────────────
  {
    slug: 'classic-5x3',
    group: 'starters',
    title: 'Classic 5×3 starter',
    oneLiner: 'The foundation of 95% of slot games. copy-paste starting point for line-pays.',
    steps: [
      'Build a 5-reel × 3-row ReelSet with your sprite atlas',
      'Handle spin + call spotlight.cycle on wins',
      'Ship',
    ],
    apis: ['ReelSetBuilder', 'SpriteSymbol', 'SymbolSpotlight.cycle'],
    tags: ['starter', '5x3', 'line-pays'],
  },
  {
    slug: 'cascade-6x5',
    group: 'starters',
    title: 'Cascade 6×5 tumble',
    oneLiner: 'Modern tumble mechanic with an ever-growing multiplier. MultiWays-adjacent.',
    steps: [
      'Build a 6×5 ReelSet with .tumble({ fall, dropIn }) for drop-in mechanics',
      'Spin, detect cluster/line wins, spotlight them',
      'Tumble (remove winners, then reelSet.refill({ winners, grid })) and repeat',
      'Each tumble increments the win multiplier',
    ],
    apis: ['ReelSetBuilder.tumble', 'ReelSet.refill', 'ReelSet.setDropOrder', 'ReelSet.setResult'],
    tags: ['starter', 'cascade', '6x5'],
  },
  {
    slug: 'tumble-feels',
    group: 'cascade',
    title: 'Tumble feels. every preset',
    oneLiner: 'Five interactive canvases. same spin + cascade-refill, only .tumble({ fall, dropIn }) changes. Click each to compare feels.',
    steps: [
      'Same builder + same scripted spin on every canvas',
      'Only the .tumble({ fall, dropIn }) shape differs between them',
      'Pick whichever reads right for your art / theme / pace',
    ],
    apis: ['ReelSetBuilder.tumble', 'ReelSet.refill', 'TumbleFallConfig', 'TumbleDropInConfig'],
    tags: ['cascade', 'tumble', 'presets', 'recent'],
  },
  {
    slug: 'refill-orders',
    group: 'cascade',
    title: 'Cascade refill orders',
    oneLiner: 'Four interactive canvases. same destruction, only the post-win refill ordering changes. Simultaneous, LTR wave, bottom-up, top-down.',
    steps: [
      'Initial reveal is identical (LTR wave) on every canvas',
      'Winners destruct the same way; the post-removal pause is fixed',
      'Only the refill drop-in order differs (setDropOrder + rowStagger + rowOrder)',
    ],
    apis: ['ReelSet.refill', 'ReelSet.setDropOrder', 'TumbleDropInConfig.rowStagger', 'TumbleDropInConfig.rowOrder'],
    tags: ['cascade', 'tumble', 'refill', 'presets', 'recent'],
  },
  {
    slug: 'tumble-anticipation',
    group: 'cascade',
    title: 'Cascade anticipation refill',
    oneLiner: 'Two-stage refill: survivors slide down first, then a global anticipation beat for multipliers / mascots, then new symbols drop in column by column.',
    steps: [
      'Initial reveal is a normal left-to-right wave',
      'Winners destruct, then survivors slide down (cascade:gravity:* events fire)',
      'Global gravityHoldMs window. plug anticipation visuals in here',
      'New symbols drop in from above, column by column (cascade:dropIn:* events)',
    ],
    apis: ['ReelSet.refill', 'RunCascadeOptions.refillMode', 'RunCascadeOptions.gravityHoldMs', 'RunCascadeOptions.onGravityComplete'],
    tags: ['cascade', 'tumble', 'refill', 'two-stage', 'anticipation', 'recent'],
  },
  {
    slug: 'fall-delays',
    group: 'cascade',
    title: 'Lead-in delay before the fall',
    oneLiner: 'Four interactive canvases. same spin, only the gap between SPIN click and the first frame of fall-out varies. From 0 ms (instant) to 700 ms (dramatic).',
    steps: [
      'Click SPIN. handler runs immediately',
      'Optionally await a lead-in pause (0 / 150 / 350 / 700 ms)',
      'Call reelSet.spin(). the fall begins',
    ],
    apis: ['ReelSet.spin', '(user-code: await wait(ms))'],
    tags: ['cascade', 'tumble', 'lead-in', 'pacing', 'recent'],
  },
  {
    slug: 'hold-and-win',
    group: 'starters',
    title: 'Hold & Win respin',
    oneLiner: 'Coins lock on land, respin until the grid fills. the "coin" formula every studio is shipping.',
    steps: [
      'Build the board once with HoldAndWinBuilder — grid, coin symbols, respin count',
      'enter(seed) with the triggering coins, then await respin(hits) per round',
      'Board events drive the HUD — respins:changed, coin:locked, board:full',
      'board:full fires the GRAND when the grid fills; reset() clears it for the next round',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.respin', 'HoldAndWinBoard.events', 'HoldAndWinBoard.reset'],
    tags: ['starter', 'hold-and-win', 'respin'],
  },
  {
    slug: 'hold-and-win-spine',
    group: 'starters',
    title: 'Hold & Win: Spine coins + collect',
    oneLiner: 'The hold & win board with production-style Spine coins. real skeletons per cell, MINI/MAJOR jackpot coins that reveal their tier on lock, side plaques that celebrate, and a collect flight that drains the board into a Spine counter.',
    steps: [
      'Register each id against its Spine skeleton via a spineMap (the jackpot coin uses a small custom class for its tier reveal)',
      'Jackpot coins land wearing their tier word; on lock the reveal spins it off into the money face',
      'coin:locked paints value labels and flashes the matching MINI / MAJOR plaque',
      'On feature end, release() each cell and fly a Spine clone to the counter via cellCenter()',
    ],
    apis: ['HoldAndWinBuilder', 'SpineReelSymbol', 'HoldAndWinBoard.release', 'HoldAndWinBoard.cellCenter'],
    tags: ['starter', 'hold-and-win', 'spine', 'collect', 'recent'],
  },
  {
    slug: 'hold-and-win-collector',
    group: 'starters',
    title: 'Hold & Win: collector + flight choreography',
    oneLiner: 'Opens holding three 5.00 coins; a 10.00 lands, then a collector orb pulls a value clone out of every coin along bezier arcs, summing tick by tick. Next press resets with a column-wave sweep.',
    steps: [
      'The board opens pre-seeded - enter(seed) runs at boot, before any spin',
      'coinWaves() picks the choreography: sequence / by-row / by-col / all / index chunks',
      'Value-label clones bezierFly() into the collector; the sum ticks up per arrival',
      'Land effects gate the next respin; the next press sweeps out and reseeds',
    ],
    apis: ['HoldAndWinBuilder', 'coinWaves', 'bezierFly', 'HoldAndWinBoard.symbolAt'],
    tags: ['starter', 'hold-and-win', 'collector', 'flight', 'spine', 'recent'],
  },

  // ── Hold & Win mechanic recipes (board + Spine coins) ──────────────
  {
    slug: 'board-grid-reveal',
    group: 'features',
    title: 'Board primitive: build your own board',
    oneLiner: 'A reveal-and-collect prize grid built directly on the generic BoardGrid primitive — every cell spins independently to a result you choose, and the rule is yours. Hold & Win is just one opinionated board on the same primitive.',
    steps: [
      'new BoardGrid({ cols, rows, cellSize, symbols, ticker }) lays out a grid of independent reels',
      'A per-cell profile function gives the diagonal stagger wave',
      'spinCells(targets) spins each cell to a result YOU choose; await the whole wave',
      'Your own rule tallies the prizes and pops the top cell via symbolAt + cellBounds',
    ],
    apis: ['BoardGrid', 'BoardGrid.spinCells', 'BoardGrid.symbolAt', 'BlurSpriteSymbol'],
    tags: ['board', 'primitive', 'boardgrid', 'build-your-own', 'recent'],
  },
  {
    slug: 'hold-and-win-trace',
    group: 'features',
    title: 'Hold & Win: live event trace',
    oneLiner: 'A board runs a full feature while every board.events beat prints to a live log — feature:enter, respin:start, cell:landed, coin:locked, respins:changed, respin:end, board:full / feature:end. The lifecycle, made visible.',
    steps: [
      'Build a plain HoldAndWinBuilder board and subscribe to every event',
      'enter(seed) opens the feature; a respin loop drives waves until done',
      'Each event appends a colour-coded line to an on-canvas log, in fire order',
      'Nothing touches board internals — the trace only listens',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.events', 'HoldAndWinBoard.phase'],
    tags: ['hold-and-win', 'events', 'lifecycle', 'debugging', 'recent'],
  },
  {
    slug: 'hold-and-win-sprites',
    group: 'features',
    title: 'Hold & Win: sprite coins (no Spine)',
    oneLiner: 'The whole board from TexturePacker sprites — number symbols that blur as they spin and a 30-frame coin flip on land. The sprite path that ships most often, no skeleton runtime.',
    steps: [
      'loadHoldAndWinSprites() returns base + blur textures, coin frames and the value font',
      'Register number symbols on BlurSpriteSymbol (blur on spin, crisp on land)',
      "Register the coin on AnimatedSpriteSymbol — the board's playWin() plays the flip",
      'Everything else is the same HoldAndWinBuilder board as the Spine recipes',
    ],
    apis: ['HoldAndWinBuilder', 'loadHoldAndWinSprites', 'BlurSpriteSymbol', 'AnimatedSpriteSymbol'],
    tags: ['hold-and-win', 'sprites', 'animated-sprite', 'blur', 'coins', 'recent'],
  },
  {
    slug: 'hold-and-win-multiplier',
    group: 'features',
    title: 'Hold & Win: multiplier-strike coin',
    oneLiner: "A multiplier coin lands, the strike FX fires over it, a ×N badge pops in the game's multiplier font, and every coin's value is multiplied. The board never reads the multiplier.",
    steps: [
      'Land a multiplier coin via the board (server-placed, carries data.mult)',
      'After the coin lands, play the 17-frame strike AnimatedSprite over the cell and pop a ×N badge',
      "Multiply every value coin's data.value and bump its label",
      'The board stays value-blind — the multiply is pure game state',
    ],
    apis: ['HoldAndWinBuilder', 'loadHoldAndWinSprites', 'HoldAndWinBoard.lockedCoins', 'PIXI.AnimatedSprite'],
    tags: ['hold-and-win', 'multiplier', 'sprites', 'fx', 'coins', 'recent'],
  },
  {
    slug: 'hold-and-win-collector-particles',
    group: 'features',
    title: 'Hold & Win: collector with particle streams',
    oneLiner: "A collector lands and each coin's value flies into it on a bezier arc trailed by a stream of neon particles, ticking the total up. The board hands out geometry; the flight is yours.",
    steps: [
      'The board opens holding value coins; a collector lands (server-placed)',
      'For each coin, fly the value into the collector on a bezier arc',
      'Trail each flight with a stream of neon particle sprites',
      'release() the cell and tick the collector total on arrival',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.cellCenter', 'HoldAndWinBoard.release', 'bezierFly'],
    tags: ['hold-and-win', 'collector', 'particles', 'sprites', 'collect', 'recent'],
  },
  {
    slug: 'hold-and-win-bonus-cell',
    group: 'features',
    title: 'Hold & Win: bonus cells',
    oneLiner: 'A few cells are marked bonus cells from the start; a coin that lands on one flashes the cell active and doubles its value. Positional rules are pure game state.',
    steps: [
      'Mark a set of cells as bonus cells and draw a glowing marker on each',
      "On coin:locked, check whether the coin's cell is a bonus cell",
      'If so, flash the marker active, fade it out and double that coin',
      'Repaint the boosted label — the board is untouched',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.events', 'HoldAndWinBoard.cellCenter', 'loadHoldAndWinSprites'],
    tags: ['hold-and-win', 'bonus-cell', 'positional', 'sprites', 'recent'],
  },
  {
    slug: 'hold-and-win-mystery-coin',
    group: 'features',
    title: 'Hold & Win: mystery value coin',
    oneLiner: 'Coins land blank; on lock a strip of candidate amounts spins inside the coin face and decelerates onto the real value. The value lives in coin.data — the board never reads it.',
    steps: [
      'Coins land settled on the gold money face with no number painted yet',
      'On coin:locked, scroll a masked strip of candidate amounts inside the coin and ease it onto the real value',
      'Paint the final amount and play the coin flourish as the "ding"',
      'Gate the next respin on the pending reveals so nothing lands mid-roll',
    ],
    apis: ['HoldAndWinBuilder', 'GoldCoinSymbol', 'HoldAndWinBoard.symbolAt', 'HoldAndWinBoard.events'],
    tags: ['hold-and-win', 'coins', 'mystery', 'reveal', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-payer-coin',
    group: 'features',
    title: 'Hold & Win: payer / doubler coin',
    oneLiner: 'A special payer orb lands and pumps its value into every other coin — a gold token arcs to each one and bumps it on arrival. One line changes it into a doubler.',
    steps: [
      'Open the board holding value coins; the payer is server-placed (weight 0)',
      "On the payer's lock, walk board.lockedCoins and fly a gold token to each coin",
      'On arrival, bump that coin\'s data.value, repaint the label and flash it',
      'The board stays value-blind — the bump is pure game state',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.lockedCoins', 'bezierFly', 'coinWaves'],
    tags: ['hold-and-win', 'coins', 'payer', 'collector', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-upgrade-coin',
    group: 'features',
    title: 'Hold & Win: upgrade a coin in place',
    oneLiner: 'A held coin climbs the value ladder (5 → 10 → 25 → 50 → 100) with a flip-and-pop — no respin, no cell movement. The new tier lives in coin.data.',
    steps: [
      'Open the board holding coins at the lowest tier',
      'On each press, bump every held coin one rung up the ladder',
      "Play the coin's one-turn flourish and pop the new amount in",
      'The board is untouched — only coin.data and the label change',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.symbolAt', 'GoldCoinSymbol'],
    tags: ['hold-and-win', 'coins', 'upgrade', 'transform', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-countup-coin',
    group: 'features',
    title: 'Hold & Win: count-up coin',
    oneLiner: "Each coin's amount ticks up from 0.00 to its value as it settles, in a reading-order wave, instead of snapping to the number.",
    steps: [
      'Land a coin and paint a 0.00 label on its face',
      'Tween a { v } counter to coin.data.value, rewriting the label every frame',
      'Pop the final width-fitted amount in when the count finishes',
      'coinWaves orders the count-ups into a wave',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.cellCenter', 'coinWaves'],
    tags: ['hold-and-win', 'coins', 'count-up', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-anticipation',
    group: 'tension',
    title: 'Hold & Win: last-cell anticipation',
    oneLiner: "One builder knob slows the last still-spinning cell to a tension profile — the 'one more for the full board' moment. The recipe only listens to events.",
    steps: [
      'Build with anticipateWhen(({ locked, capacity }) => capacity - locked === 1)',
      "When one cell is left, the board runs it on the 'tension' profile",
      'respin:start tells you which cells spin — pulse the last one',
      'board:full / isFull report the jackpot',
    ],
    apis: ['HoldAndWinBuilder.anticipateWhen', 'HoldAndWinBoard.events', 'HoldAndWinBoard.isFull'],
    tags: ['hold-and-win', 'anticipation', 'tension', 'respin', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-meter',
    group: 'features',
    title: 'Hold & Win: fly to a feature meter',
    oneLiner: "On collect, each coin's value flies UP into a meter above the reels (arriveScale shrink), ticking the total and filling a progress bar toward a target.",
    steps: [
      'Place a meter widget (spine counter + bar + total) above the board',
      'Fly each value from cellCenter() up to the meter with arriveScale',
      'On arrival, add to the total, fill the bar and tick the counter',
      'release() each cell as its coin leaves',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.cellCenter', 'HoldAndWinBoard.release', 'bezierFly'],
    tags: ['hold-and-win', 'coins', 'meter', 'collect', 'flight', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-row-jackpot',
    group: 'features',
    title: 'Hold & Win: row-complete jackpot',
    oneLiner: 'When a coin completes a full row, that row flashes coin by coin, the MINI plaque fires, and the row total flies up into it. Row detection is pure game logic.',
    steps: [
      'On coin:locked, check whether the new coin completed a full row',
      "If it did, flash the row coin by coin and fire the MINI plaque's win",
      'Sum the row and fly the total up into the plaque',
      'Gate the next press until the choreography settles',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.events', 'HoldAndWinBoard.symbolAt', 'bezierFly'],
    tags: ['hold-and-win', 'coins', 'jackpot', 'row', 'plaque', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-base-to-feature',
    group: 'features',
    title: 'Hold & Win: enter from the base game and back',
    oneLiner: 'A normal 5x3 spin that, on 3 BONUS, transitions in the same chain into the Hold & Win board, runs the feature, and swaps back to the base game on feature:end. Two display objects, one Spin button.',
    steps: [
      'Spin a normal ReelSet; count the BONUS symbols that land',
      'On a 3-BONUS trigger, hide the base reels and reveal board.container',
      'enter(seed) carries the trigger coins into the feature already locked',
      'On feature:end, fade the board out and show the base game again',
    ],
    apis: ['ReelSetBuilder', 'HoldAndWinBuilder', 'HoldAndWinBoard.enter', 'HoldAndWinBoard.events'],
    tags: ['hold-and-win', 'base-game', 'transition', 'feature', 'trigger', 'recent'],
  },
  {
    slug: 'hold-and-win-cell-control',
    group: 'features',
    title: 'Hold & Win: drive each cell on its own',
    oneLiner: 'board.reelAt(cell) hands you the raw 1x1 ReelSet — start it, slam-stop it, read the symbol inside it, independently of every other cell.',
    steps: [
      "board.reelAt(cell) returns that cell's ReelSet",
      'Start cells on their own clocks (staggered) — each is independent',
      'Slam-stop a single cell with reelAt(cell).skipSpin() while others spin',
      'Read the live symbol with symbolAt(cell)',
    ],
    apis: ['HoldAndWinBoard.reelAt', 'HoldAndWinBoard.symbolAt', 'ReelSet.spin', 'ReelSet.skipSpin'],
    tags: ['hold-and-win', 'cell', 'reel', 'control', 'start-stop', 'recent'],
  },
  {
    slug: 'hold-and-win-tier-swap',
    group: 'features',
    title: 'Hold & Win: swap a symbol in place (coin → MINI → MAJOR)',
    oneLiner: "board.setSymbolAt(cell, id, data) re-places one cell with a different symbol — a coin climbs the jackpot tiers — and rewrites its ledger entry, leaving every other coin where it was.",
    steps: [
      'Register the plain coin and the MINI / MAJOR jackpot variants',
      'On each press, board.setSymbolAt(cell, tierId, data) swaps the art in place',
      "The cell's ledger entry is rewritten so lockedCoins / totals stay correct",
      'Neighbouring coins are untouched',
    ],
    apis: ['HoldAndWinBoard.setSymbolAt', 'HoldAndWinBoard.symbolAt', 'SpineReelSymbol'],
    tags: ['hold-and-win', 'swap', 'jackpot', 'tier', 'upgrade', 'spine', 'recent'],
  },
  {
    slug: 'hold-and-win-sticky-overlay',
    group: 'features',
    title: 'Hold & Win: an overlay that survives swaps and rides flights',
    oneLiner: "A ×100 badge lives in coin.data, attached as a child of the symbol's view — so it survives an in-place swap (re-attached from data) and travels with the coin on a collect flight.",
    steps: [
      'Keep the overlay value in coin.data (badge, jackpot label)',
      'Attach it as a CHILD of symbolAt(cell).view so it rides with the symbol',
      'On an in-place swap, re-attach from coin.data (the new instance has a fresh view)',
      'On a flight, rebuild it onto the flying clone from the same data',
    ],
    apis: ['HoldAndWinBoard.symbolAt', 'HoldAndWinBoard.setSymbolAt', 'HoldAndWinBoard.cellCenter', 'bezierFly'],
    tags: ['hold-and-win', 'overlay', 'badge', 'swap', 'flight', 'recent'],
  },
  {
    slug: 'hold-and-win-skip',
    group: 'tension',
    title: 'Hold & Win: skip the whole feature',
    oneLiner: 'board.skip() slams every in-flight cell to its landed position and fires feature:skip; the game layer cuts its flights / collect short. feature:end stays the single "feature over" signal.',
    steps: [
      'Tap the button mid-feature — RecipeRunner routes it to onSkip',
      'onSkip calls board.skip() to slam every in-flight spin (fires feature:skip)',
      'The game layer cuts its own flights / collect short on the same signal',
      'feature:end fires as the single "feature over" event',
    ],
    apis: ['HoldAndWinBoard.skip', 'HoldAndWinBoard.events', 'ReelSet.skipSpin'],
    tags: ['hold-and-win', 'skip', 'fast-forward', 'events', 'recent'],
  },

  // ── Mechanic recipes ───────────────────────────────────────────────
  {
    slug: 'symbol-transform',
    group: 'features',
    title: 'Symbol transform',
    oneLiner: 'A symbol morphs into a different (usually higher) one mid-round. winning lows upgrade to meds.',
    steps: [
      'Detect the transform trigger (a win, a cascade level, an RNG roll)',
      'Tween the old symbol out (scale / fade / disintegrate)',
      'Swap the symbol via reel.placeSymbols with the new identity',
      'Tween the new symbol in',
    ],
    apis: ['Reel.placeSymbols', 'Reel.getSymbolAt', 'ReelSymbol.view'],
    tags: ['transform', 'animation', 'upgrade'],
  },

  // ── UX & system recipes ────────────────────────────────────────────
  {
    slug: 'remove-symbol',
    group: 'cascade',
    title: 'Remove symbol in a cascade',
    oneLiner: 'Fade winners out, then drop the next-stage symbols in from above. no reel respin.',
    steps: [
      'Detect winning cells on the visible grid',
      'reelSet.destroySymbols(winners) fades them out',
      'reelSet.refill({ winners, grid }) slides survivors and drops new symbols from above',
    ],
    apis: ['ReelSet.destroySymbols', 'ReelSet.refill', 'ReelSet.runCascade'],
    tags: ['cascade', 'animation'],
  },
  {
    slug: 'anticipate-a-reel',
    group: 'tension',
    title: 'Anticipate a reel',
    oneLiner: 'Slow a specific reel to build tension before it lands.',
    steps: [
      'During spin, detect interesting partial state',
      'Call reelSet.setAnticipation([...reelIndices])',
      'Then call setResult(). the marked reels enter ANTICIPATION before STOP',
    ],
    apis: ['ReelSet.setAnticipation', 'spin:stopping event', 'AnticipationPhase'],
    tags: ['anticipation', 'tension'],
  },
  {
    slug: 'peek-from-above',
    group: 'tension',
    title: 'Peek symbol from buffer-above',
    oneLiner: 'Pre-fill the buffer-above slot so a teaser symbol sits just out of frame, visible during scroll-in on the next spin.',
    steps: [
      'Seed initialFrame with a ColumnTarget that sets bufferAbove at build time',
      'On every spin, pass the same { visible, bufferAbove } shape to setResult so the teaser carries forward',
      'When the next spin starts, that symbol is the first to scroll into the visible area',
    ],
    apis: ['ReelSetBuilder.initialFrame', 'ReelSet.setResult', 'ColumnTarget'],
    tags: ['buffer', 'peek', 'tension', 'reveal'],
  },
  {
    slug: 'anticipation-teaser',
    group: 'tension',
    title: 'Anticipation teaser',
    oneLiner: 'Pair setAnticipation with a buffer-above prefill so the next cell to scroll into view on a slow reel is a caller-chosen symbol.',
    steps: [
      'Call setAnticipation([...reels]) to slow specific reels before they land',
      "Pass a ColumnTarget with bufferAbove: ['BONUS'] on those same reels so the symbol sits one slot above the visible window",
      'During anticipation deceleration, the buffer-above cell is the next to enter view',
    ],
    apis: ['ReelSet.setAnticipation', 'ReelSet.setResult', 'AnticipationPhase'],
    tags: ['anticipation', 'tension', 'buffer', 'peek'],
  },
  {
    slug: 'paylines-custom-animation',
    group: 'wins',
    title: 'Custom per-symbol animation',
    oneLiner: 'Replace playWin() with a GSAP timeline, styled per win.id.',
    steps: [
      'Pass symbolAnim as a callback or named animation',
      'Receive (symbol, cell, win). return a Promise',
      'Style per win via win.id or win.kind',
    ],
    apis: ['WinPresenter.symbolAnim', 'WinSymbolAnim'],
    tags: ['wins', 'gsap'],
  },
  {
    slug: 'cascade-winpresenter',
    group: 'cascade',
    title: 'Cascade pops with WinPresenter',
    oneLiner: 'Same presenter, same Win shape. just cells vanishing from a cascade.',
    steps: [
      'Build a WinPresenter',
      'In runCascade\'s onWinnersVanish, await presenter.show([{ cells }])',
      'Tumble + drop continues once the pop resolves',
    ],
    apis: ['WinPresenter', 'runCascade.onWinnersVanish', 'win:group'],
    tags: ['wins', 'cascade'],
  },
  {
    slug: 'spin-then-cascade',
    group: 'cascade',
    title: 'Spin first, cascade after',
    oneLiner: 'Open every play with a classic strip-spin, then cascade the respins. one ReelSet, the per-spin mode override does the switch.',
    steps: [
      'Build with a default mode AND .tumble(...) registered',
      'Round 1. call spin() (default standard)',
      'Cascade respins. call spin({ mode: "cascade" }) per round',
    ],
    apis: ['ReelSetBuilder.tumble', 'reelSet.spin', 'SpinOptions.mode'],
    tags: ['hybrid', 'cascade', 'spin-mode', 'recent'],
  },
  {
    slug: 'paylines-events-only',
    group: 'wins',
    title: 'Draw paylines yourself from win:group',
    oneLiner: 'Core never draws lines. Subscribe to win:group + getCellBounds and render any overlay.',
    steps: [
      'Subscribe to win:group',
      'Use reelSet.getCellBounds to plot a polyline or outline',
      'Drop visuals into your own PIXI.Container',
    ],
    apis: ['ReelSet.getCellBounds', 'win:group', 'win:symbol'],
    tags: ['wins', 'events', 'overlays'],
  },
  {
    slug: 'slam-stop',
    group: 'tension',
    title: 'Slam-stop',
    oneLiner: 'Let the player smash the button to land the reels now.',
    steps: [
      'On spin click: if isSpinning, call reelSet.skipSpin(). Otherwise reelSet.spin()',
      'First skipSpin() in a round lands the spin AND applies a side effect (speed boost in standard mode; auto-slam future refills in cascade). Subsequent presses also slam',
      'Use requestSkip() when result may not be in yet, or slamStop() for an unconditional land (tests, anti-cheat)',
      'Inspect result.wasSkipped on the returned promise',
    ],
    apis: ['ReelSet.skipSpin', 'ReelSet.requestSkip', 'ReelSet.slamStop', 'ReelSet.skipStage', 'ReelSet.isSpinning', 'SpinResult.wasSkipped'],
    tags: ['skip', 'UX'],
  },
  {
    slug: 'near-miss',
    group: 'tension',
    title: 'Fake a near-miss',
    oneLiner: 'Place N-1 scatters plus anticipation on the reel that "almost" landed one.',
    steps: [
      'Build a result grid with only count - 1 scatters, none on nearReel',
      'Call setAnticipation([nearReel]) before setResult()',
      'Let the player feel the hold on the last reel',
    ],
    apis: ['ReelSet.setAnticipation', 'forceNearMiss cheat'],
    tags: ['anticipation', 'near-miss'],
  },
  {
    slug: 'nudge',
    group: 'tension',
    title: 'Nudge a reel',
    oneLiner: 'After landing, shift one reel down or up by N positions to reveal caller-supplied symbols.',
    steps: [
      'Wait for the spin to land',
      'Call reelSet.nudge(col, { distance, direction, incoming }). incoming is required, top-down order of the new visible positions',
      'Await the promise to read the new visible column for re-running win detection',
      'Wrap several nudge() calls in Promise.all([...]) to move multiple reels in parallel',
    ],
    apis: ['ReelSet.nudge', 'NudgeOptions', 'nudge:start', 'nudge:complete'],
    tags: ['nudge', 'recent'],
  },
  {
    slug: 'nudge-spotlight',
    group: 'tension',
    title: 'Spotlight after a nudge',
    oneLiner: 'Land a near-miss, parallel-nudge three reels to complete a wild line, then run SymbolSpotlight on the new winners. Chains nudge() and spotlight.show() in their canonical order.',
    steps: [
      'Spin and land on a flat near-miss',
      'Promise.all three reelSet.nudge calls so the middle reels drop in `wild` together',
      'Build win cells from the nudged reels and call reelSet.spotlight.show(...)',
      'Await spotlight completion, then spotlight.hide()',
    ],
    apis: ['ReelSet.nudge', 'ReelSet.spotlight.show', 'ReelSet.spotlight.hide', 'nudge:complete'],
    tags: ['nudge', 'spotlight', 'wins', 'recent'],
  },
  {
    slug: 'nudge-skip',
    group: 'tension',
    title: 'Skip an in-flight nudge',
    oneLiner: 'reelSet.skipNudge(col) fast-forwards a running nudge tween to its landed position. The original nudge() promise resolves normally. success path still runs.',
    steps: [
      'Run a long nudge so the player has time to react',
      'On the player\'s tap during the nudge, call reelSet.skipNudge(col)',
      'The tween jumps to its landed state, nudge() resolves on the next microtask',
      'Strip lands at the deterministic post-nudge position regardless',
    ],
    apis: ['ReelSet.skipNudge', 'Reel.isNudging'],
    tags: ['nudge', 'skip', 'ux', 'recent'],
  },
  {
    slug: 'nudge-abort',
    group: 'tension',
    title: 'Abort a nudge',
    oneLiner: 'Cancel a running nudge via NudgeOptions.signal. Strip still snaps to landed; nudge() rejects with AbortError; nudge:cancelled fires on the bus.',
    steps: [
      'Wire an AbortController into NudgeOptions.signal',
      'Trigger the abort while the tween is running',
      'Catch AbortError to take the cancellation path; non-abort errors re-throw',
      'nudge:cancelled fires on the reel-set bus carrying the reason',
    ],
    apis: ['NudgeOptions.signal', 'AbortController', 'nudge:cancelled'],
    tags: ['nudge', 'abort', 'cancellation', 'recent'],
  },
  {
    slug: 'nudge-stagger',
    group: 'tension',
    title: 'Staggered nudge. wave reveal',
    oneLiner: 'Promise.all + NudgeOptions.startDelay dispatches every reel\'s tween concurrently with a per-reel offset. Total wall time is (cols.length - 1) * stagger + duration.',
    steps: [
      'Promise.all over the target reels with startDelay: i * STAGGER_MS',
      'Total wall time = (cols.length - 1) * stagger + duration',
      'Validation throws still fire synchronously. only the mutation defers',
      'Cancel mid-wave with an AbortSignal; reels in startDelay bail before mutating',
    ],
    apis: ['ReelSet.nudge', 'NudgeOptions.startDelay'],
    tags: ['nudge', 'stagger', 'wave', 'recent'],
  },
  {
    slug: 'nudge-big-symbol',
    group: 'tension',
    title: 'Nudge through a big symbol',
    oneLiner: 'A 1xH block on the target reel is nudged through as a unit. Survival formula enforced; cross-reel (w>1) blocks throw.',
    steps: [
      'Land with a 1x2 wild at rows 0+1',
      'Nudge DOWN by 2. block survives (anchor + h + distance < total), lands half-visible',
      'Nudge UP by 1. block returns to full visibility',
      'Cross-reel blocks throw; in-flight wrap never splits anchor from stubs',
    ],
    apis: ['ReelSet.nudge', 'SymbolData.size'],
    tags: ['nudge', 'big-symbols', 'block', 'recent'],
  },
  {
    slug: 'texture-atlas-symbols',
    group: 'symbol-formats',
    title: 'Texture atlas symbols',
    oneLiner: 'Load sprite symbols from a TexturePacker atlas. one atlas file, 80+ frames.',
    steps: [
      'Load the TexturePacker JSON with PIXI.Assets.load(). PixiJS understands the format natively',
      'The returned Spritesheet exposes sheet.textures[frameId] for every frame',
      'Pass the base + blur texture maps to SpriteSymbol or BlurSpriteSymbol',
    ],
    apis: ['PIXI.Assets.load', 'Spritesheet.textures', 'SpriteSymbol', 'BlurSpriteSymbol'],
    tags: ['sprites', 'atlas', 'texturepacker'],
  },
  // ── CellPin primitive recipes ──────────────────────────────────────
  // These recipes all use reelSet.pin(). the engine's unified cell-persistence
  // primitive. Each shows a different configuration of one API.
  {
    slug: 'sticky-wild-pin',
    group: 'wilds',
    title: 'Sticky wild (CellPin)',
    oneLiner: 'Same sticky wild, built on the engine primitive. no ghost sprites, no manual grid injection.',
    steps: [
      'Listen for wilds landing via spin:allLanded',
      'Call reelSet.pin(col, row, "wild", { turns: N })',
      'The engine overlays the pin on setResult and decrements turns automatically',
    ],
    apis: ['ReelSet.pin', 'ReelSet.getPin', 'pin:expired event'],
    tags: ['wild', 'sticky', 'cell-pin'],
  },
  {
    slug: 'expanding-wild-pin',
    group: 'wilds',
    title: 'Expanding wild',
    oneLiner: 'Wild lands, entire column becomes wild for N spins. auto-expires when the turn counter runs out.',
    steps: [
      'On spin:allLanded, find every reel containing a wild',
      'Pin every row of that reel with { turns: N }. the column stays wild for N more spins',
      'The engine decrements turns after each spin:allLanded and expires pins at zero',
    ],
    apis: ['ReelSet.pin', 'CellPin.turns (number)'],
    tags: ['wild', 'expanding', 'sticky', 'cell-pin'],
  },
  {
    slug: 'multiplier-wild-pin',
    group: 'wilds',
    title: 'Multiplier wild',
    oneLiner: 'Each wild carries a per-instance multiplier in its pin payload. a ×N badge overlays the cell.',
    steps: [
      'Pin wilds on land with a payload containing the multiplier value',
      'Draw a ×N badge on each pinned cell via pin:placed event',
      'On wins, read pin.payload.multiplier to scale the payout',
    ],
    apis: ['ReelSet.pin', 'CellPin.payload', 'pin:placed event'],
    tags: ['wild', 'multiplier', 'payload', 'cell-pin'],
  },
  {
    slug: 'value-coin-pin',
    group: 'features',
    title: 'Value-carrying coin (Hold & Win)',
    oneLiner: 'Each coin carries a coefficient (×2 … ×50) in coin.data; the board locks hits and respins only the free cells natively — no pins, no hand-rolled grid. The ×N badge is painted from data, the total summed from board.lockedCoins.',
    steps: [
      'Build the board with HoldAndWinBuilder; coins are opaque { cell, id, data }',
      'Each hit carries its coefficient in data.value',
      'Paint the ×N badge from data on coin:locked',
      'Sum the running total from board.lockedCoins',
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.respin', 'HoldAndWinBoard.lockedCoins', 'HoldAndWinBoard.events'],
    tags: ['coin', 'hold-and-win', 'value', 'data', 'recent'],
  },
  {
    slug: 'collector-symbol-pin',
    group: 'features',
    title: 'Collector symbol',
    oneLiner: 'On the Hold & Win board, the collector orb absorbs its neighbours: walk board.lockedCoins, sum the adjacent coins, fly their values in and release() those cells. No pins.',
    steps: [
      'Build the board with HoldAndWinBuilder; coins carry data.value',
      'When the collector locks, find its neighbours in board.lockedCoins',
      'Fly each neighbour value into the orb and release() the cell',
      "Show the absorbed total on the collector's badge",
    ],
    apis: ['HoldAndWinBuilder', 'HoldAndWinBoard.lockedCoins', 'HoldAndWinBoard.release', 'bezierFly'],
    tags: ['coin', 'collector', 'hold-and-win', 'recent'],
  },
  {
    slug: 'mystery-reveal-pin',
    group: 'features',
    title: 'Mystery reveal (CellPin)',
    oneLiner: 'Mystery symbols land, all reveal to the same random class via eval pins. auto-cleared at next spin.',
    steps: [
      'Server places "mystery" symbols at specific cells',
      'On spin:allLanded, pick one random class and pin all mystery cells with { turns: "eval" }',
      'Pins auto-clear on next spin:start',
    ],
    apis: ['ReelSet.pin', 'CellPin.turns ("eval")'],
    tags: ['mystery', 'reveal', 'cell-pin'],
  },
  {
    slug: 'sticky-win-respin-pin',
    group: 'wilds',
    title: 'Sticky-win respin',
    oneLiner: 'Winners lock for N respins while the rest of the grid spins independently. the Dead-or-Alive-II pattern.',
    steps: [
      'Detect winners on spin:allLanded',
      'Pin each winner with { turns: N }. N is the respin window',
      'Non-winners respin naturally; winners stay pinned and expire after N spins',
    ],
    apis: ['ReelSet.pin', 'CellPin.turns (number)', 'pin:expired event'],
    tags: ['respin', 'sticky', 'win', 'cell-pin'],
  },
  {
    slug: 'positional-multiplier-pin',
    group: 'features',
    title: 'Positional multiplier cells',
    oneLiner: 'Specific cells carry multipliers. any symbol that lands there boosts the win passing through.',
    steps: [
      'Mark fixed cells as multiplier positions (or receive them per-spin from server)',
      'Draw persistent ×N badges at those cells',
      'After landing, pin the rolled symbol with multiplier in payload (turns "eval")',
    ],
    apis: ['ReelSet.pin', 'CellPin.payload', 'CellPin.turns ("eval")'],
    tags: ['multiplier', 'positional', 'payload', 'cell-pin'],
  },

  // ── getCellBounds. coordinate utilities ──────────────────────────────
  {
    slug: 'cell-bounds',
    group: 'cell-coords',
    title: 'Cell bounds. overlays, paylines & hit areas',
    oneLiner: 'getCellBounds(col, row) returns the pixel rectangle of any visible cell. draw paylines, win outlines, or hit areas that align exactly with symbols.',
    steps: [
      'Call reelSet.getCellBounds(col, row) to get { x, y, width, height } in ReelSet-local coords',
      'Draw a PIXI.Graphics outline or line using those coordinates',
      'addChild the graphic to reelSet so it stays aligned with the board',
    ],
    apis: ['ReelSet.getCellBounds', 'CellBounds'],
    tags: ['utility', 'paylines', 'hit-areas', 'graphics'],
  },
  {
    slug: 'cell-hit-areas',
    group: 'cell-coords',
    title: 'Cell hit areas. click to pick, hover to preview',
    oneLiner: 'Attach pointer events to individual grid cells with getCellBounds. cursor turns to pointer on hover, click toggles a pick state.',
    steps: [
      'For each cell, call reelSet.getCellBounds(col, row)',
      'Build an invisible PIXI.Graphics rect with eventMode "static" + cursor "pointer"',
      'Wire pointerover / pointerout / pointertap to drive hover + pick state',
    ],
    apis: ['ReelSet.getCellBounds', 'PIXI.Graphics.eventMode', 'PIXI.Graphics.cursor'],
    tags: ['utility', 'hit-areas', 'interaction', 'cursor'],
  },

  // ── movePin + frame exposure recipes ──────────────────────────────────
  {
    slug: 'walking-wild-pin',
    group: 'wilds',
    title: 'Walking wild (movePin)',
    oneLiner: 'Walking wild migrating one column left each spin. engine-native reelSet.movePin(), no ghost sprites.',
    steps: [
      "Pin new wilds on land with turns 'permanent'",
      'Before each spin, movePin() each existing pin one column left',
      'When a pin reaches column 0, unpin(). it has walked off the board',
    ],
    apis: ['ReelSet.pin', 'ReelSet.movePin', 'ReelSet.unpin', 'pin:moved event'],
    tags: ['wild', 'walking', 'movement', 'cell-pin'],
  },
  {
    slug: 'feature-mode-swap',
    group: 'runtime',
    title: 'Feature mode swap',
    oneLiner: 'Enter and exit a bonus mode at runtime by toggling a frame middleware. zero rebuild.',
    steps: [
      'Write a FrameMiddleware that rewrites frames for the bonus mode',
      'On feature entry, call reelSet.frame.use(middleware)',
      'On feature exit, call reelSet.frame.remove(name)',
    ],
    apis: ['ReelSet.frame.use', 'ReelSet.frame.remove', 'FrameMiddleware'],
    tags: ['mode', 'feature', 'middleware', 'frame'],
  },
];
