import { Assets } from 'pixi.js';

/**
 * Loads the bun-generated 10-symbol spine bundle from
 * `examples/assets/generated-symbols/`. Each example maps its own symbol
 * IDs onto these aliases via `SpineReelSymbol`'s `spineMap` option.
 *
 * The bundle is generated by `tools/symbol-gen` (run `bun run build` in
 * that folder); the atlas + per-symbol JSONs land alongside this loader's
 * output and are served from the examples shared `assets/` publicDir.
 */
export const GENERATED_SPINE_NAMES = [
  'low_a', 'low_k', 'low_q', 'low_j',
  'mid_1', 'mid_2', 'mid_3',
  'high_1',
  'wild', 'scatter',
] as const;

export type GeneratedSpineName = (typeof GENERATED_SPINE_NAMES)[number];

export const GENERATED_ATLAS_ALIAS = 'generated-symbols-atlas';

const DEFAULT_BASE = '/generated-symbols/';

const loaded = new Map<string, Promise<void>>();

/**
 * Idempotent per basePath: safe to call from multiple boot() invocations.
 * Loads atlas first (textures resolve relative to its directory) then
 * all 10 skeleton JSONs under their canonical alias names.
 *
 * Examples expecting `examples/assets/` as `publicDir` pass no argument.
 * The docs site serves the same files from `apps/site/public/generated-symbols/`,
 * which is the same default URL — `'generated-symbols/'` works there too.
 */
export async function loadGeneratedSpines(basePath: string = DEFAULT_BASE): Promise<void> {
  const cached = loaded.get(basePath);
  if (cached) return cached;
  const work = (async () => {
    await Assets.load({ alias: GENERATED_ATLAS_ALIAS, src: `${basePath}symbols.atlas` });
    for (const name of GENERATED_SPINE_NAMES) {
      await Assets.load({ alias: name, src: `${basePath}${name}.json` });
    }
  })();
  loaded.set(basePath, work);
  return work;
}

/**
 * Build the `spineMap` argument for `SpineReelSymbol` from a symbolId →
 * spine-name mapping. Throws (loud, not silent) if a target name isn't in
 * the generated bundle, since that's a config bug, not a runtime fallback.
 */
export function buildSpineMap(
  mapping: Record<string, GeneratedSpineName>,
): Record<string, { skeleton: string; atlas: string }> {
  const out: Record<string, { skeleton: string; atlas: string }> = {};
  for (const [id, name] of Object.entries(mapping)) {
    if (!GENERATED_SPINE_NAMES.includes(name)) {
      throw new Error(
        `[generatedSpineLoader] '${name}' is not a generated spine. ` +
        `Available: ${GENERATED_SPINE_NAMES.join(', ')}`,
      );
    }
    out[id] = { skeleton: name, atlas: GENERATED_ATLAS_ALIAS };
  }
  return out;
}
